#!/usr/bin/env php
<?php
namespace Schnittstabil\Saika\Cli;

require __DIR__ . '/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application();
$application->add(new Command\ChownCommand());
$application->run();
